// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi kubechecker
Kube-checker checks your Kubernetes cluster and provides recommendations and best practices


    Schemes:
      https
    Host: 10.10.10.10:8091
    BasePath: /
    Version: 1.0.0
    Contact: <sanket@infracloud.io> https://infracloud.io

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
