// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Kube-checker checks your Kubernetes cluster and provides recommendations and best practices",
    "title": "kubechecker",
    "contact": {
      "url": "https://infracloud.io",
      "email": "sanket@infracloud.io"
    },
    "version": "1.0.0"
  },
  "host": "10.10.10.10:8091",
  "basePath": "/",
  "paths": {
    "/v1/job_status/{job_id}": {
      "get": {
        "description": "Get Report\n",
        "produces": [
          "application/json"
        ],
        "operationId": "GetJobStatus",
        "parameters": [
          {
            "type": "string",
            "name": "job_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response will report with recommendations",
            "schema": {
              "$ref": "#/definitions/V1.Job"
            }
          }
        }
      }
    },
    "/v1/report/{report_id}": {
      "get": {
        "description": "Get Report\n",
        "produces": [
          "application/json"
        ],
        "operationId": "GetReport",
        "parameters": [
          {
            "type": "string",
            "name": "report_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response will report with recommendations",
            "schema": {
              "$ref": "#/definitions/V1.Report"
            }
          }
        }
      },
      "delete": {
        "description": "Delete report\n",
        "operationId": "DeleteReport",
        "parameters": [
          {
            "type": "string",
            "name": "report_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Delete report"
          }
        }
      }
    },
    "/v1/scan": {
      "post": {
        "description": "Create a scan job and collect Job info.\n",
        "produces": [
          "application/json"
        ],
        "operationId": "AddJob",
        "responses": {
          "200": {
            "description": "A successful response will contain list of the AZs in the configured region",
            "schema": {
              "$ref": "#/definitions/V1.Job"
            }
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Error"
          }
        }
      }
    }
  },
  "definitions": {
    "V1.Job": {
      "type": "object",
      "properties": {
        "id": {
          "description": "Job id",
          "type": "string"
        },
        "report_id": {
          "description": "Report id if job succeded",
          "type": "string"
        },
        "state": {
          "description": "Job state",
          "type": "string",
          "enum": [
            "starting",
            "running",
            "succeded",
            "aborted",
            "failed"
          ]
        }
      },
      "example": {
        "id": "id",
        "report_id": "report_id",
        "state": "starting"
      }
    },
    "V1.Recommendation": {
      "type": "object",
      "properties": {
        "info": {
          "description": "Info about recommendation",
          "type": "string"
        },
        "name": {
          "description": "Name of the recommendation",
          "type": "string"
        }
      },
      "example": {
        "info": "Please specify pod limits",
        "name": "ResourceLimitMissing"
      }
    },
    "V1.RecommendationList": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/V1.Recommendation"
      }
    },
    "V1.Report": {
      "type": "object",
      "properties": {
        "id": {
          "description": "Report id",
          "type": "string"
        },
        "recommendations": {
          "$ref": "#/definitions/V1.RecommendationList"
        }
      },
      "example": {
        "id": "id",
        "recommendations": ""
      }
    }
  }
}`))
}
