// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddJobHandlerFunc turns a function with the right signature into a add job handler
type AddJobHandlerFunc func(AddJobParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddJobHandlerFunc) Handle(params AddJobParams) middleware.Responder {
	return fn(params)
}

// AddJobHandler interface for that can handle valid add job params
type AddJobHandler interface {
	Handle(AddJobParams) middleware.Responder
}

// NewAddJob creates a new http.Handler for the add job operation
func NewAddJob(ctx *middleware.Context, handler AddJobHandler) *AddJob {
	return &AddJob{Context: ctx, Handler: handler}
}

/*AddJob swagger:route POST /v1/scan addJob

Create a scan job and collect Job info.


*/
type AddJob struct {
	Context *middleware.Context
	Handler AddJobHandler
}

func (o *AddJob) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddJobParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
