// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/infracloudio/kube-checker/pkg/models"
)

// AddJobOKCode is the HTTP code returned for type AddJobOK
const AddJobOKCode int = 200

/*AddJobOK A successful response will contain list of the AZs in the configured region

swagger:response addJobOK
*/
type AddJobOK struct {

	/*
	  In: Body
	*/
	Payload *models.V1Job `json:"body,omitempty"`
}

// NewAddJobOK creates AddJobOK with default headers values
func NewAddJobOK() *AddJobOK {
	return &AddJobOK{}
}

// WithPayload adds the payload to the add job o k response
func (o *AddJobOK) WithPayload(payload *models.V1Job) *AddJobOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add job o k response
func (o *AddJobOK) SetPayload(payload *models.V1Job) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddJobOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddJobForbiddenCode is the HTTP code returned for type AddJobForbidden
const AddJobForbiddenCode int = 403

/*AddJobForbidden Forbidden

swagger:response addJobForbidden
*/
type AddJobForbidden struct {
}

// NewAddJobForbidden creates AddJobForbidden with default headers values
func NewAddJobForbidden() *AddJobForbidden {
	return &AddJobForbidden{}
}

// WriteResponse to the client
func (o *AddJobForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// AddJobInternalServerErrorCode is the HTTP code returned for type AddJobInternalServerError
const AddJobInternalServerErrorCode int = 500

/*AddJobInternalServerError Internal Error

swagger:response addJobInternalServerError
*/
type AddJobInternalServerError struct {
}

// NewAddJobInternalServerError creates AddJobInternalServerError with default headers values
func NewAddJobInternalServerError() *AddJobInternalServerError {
	return &AddJobInternalServerError{}
}

// WriteResponse to the client
func (o *AddJobInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
