// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteReportOKCode is the HTTP code returned for type DeleteReportOK
const DeleteReportOKCode int = 200

/*DeleteReportOK Delete report

swagger:response deleteReportOK
*/
type DeleteReportOK struct {
}

// NewDeleteReportOK creates DeleteReportOK with default headers values
func NewDeleteReportOK() *DeleteReportOK {
	return &DeleteReportOK{}
}

// WriteResponse to the client
func (o *DeleteReportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
