// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/infracloudio/kube-checker/pkg/models"
)

// GetJobStatusOKCode is the HTTP code returned for type GetJobStatusOK
const GetJobStatusOKCode int = 200

/*GetJobStatusOK A successful response will report with recommendations

swagger:response getJobStatusOK
*/
type GetJobStatusOK struct {

	/*
	  In: Body
	*/
	Payload *models.V1Job `json:"body,omitempty"`
}

// NewGetJobStatusOK creates GetJobStatusOK with default headers values
func NewGetJobStatusOK() *GetJobStatusOK {
	return &GetJobStatusOK{}
}

// WithPayload adds the payload to the get job status o k response
func (o *GetJobStatusOK) WithPayload(payload *models.V1Job) *GetJobStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get job status o k response
func (o *GetJobStatusOK) SetPayload(payload *models.V1Job) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetJobStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
