// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetReportHandlerFunc turns a function with the right signature into a get report handler
type GetReportHandlerFunc func(GetReportParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetReportHandlerFunc) Handle(params GetReportParams) middleware.Responder {
	return fn(params)
}

// GetReportHandler interface for that can handle valid get report params
type GetReportHandler interface {
	Handle(GetReportParams) middleware.Responder
}

// NewGetReport creates a new http.Handler for the get report operation
func NewGetReport(ctx *middleware.Context, handler GetReportHandler) *GetReport {
	return &GetReport{Context: ctx, Handler: handler}
}

/*GetReport swagger:route GET /v1/report/{report_id} getReport

Get Report


*/
type GetReport struct {
	Context *middleware.Context
	Handler GetReportHandler
}

func (o *GetReport) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetReportParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
