// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/infracloudio/kube-checker/pkg/models"
)

// GetReportOKCode is the HTTP code returned for type GetReportOK
const GetReportOKCode int = 200

/*GetReportOK A successful response will report with recommendations

swagger:response getReportOK
*/
type GetReportOK struct {

	/*
	  In: Body
	*/
	Payload *models.V1Report `json:"body,omitempty"`
}

// NewGetReportOK creates GetReportOK with default headers values
func NewGetReportOK() *GetReportOK {
	return &GetReportOK{}
}

// WithPayload adds the payload to the get report o k response
func (o *GetReportOK) WithPayload(payload *models.V1Report) *GetReportOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get report o k response
func (o *GetReportOK) SetPayload(payload *models.V1Report) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
